@startuml Delete Bookings (DELETE)

header Delete Bookings Sequence Diagram
title "Delete Bookings (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.get('/bookings')
server->routerBookings ++:app.use('/bookings',bookings)
routerBookings -> controllersBookings ++: getBooking(req, res, next)
controllersBookings->modelBooking ++:findById(req.params.bookingId)
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: booking
controllersBookings <-- modelBooking --:booking
controllersBookings->modelBooking ++:booking.deleteOne()
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: delete_booking
controllersBookings <-- modelBooking --: delete_booking
controllersBookings->client --:response

@enduml
