@startuml Delete Single Bookings (DELETE)

header Delete Single Bookings Sequence Diagram
title "Delete Single Bookings (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:User" as modelUser
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:users" as UsersDatabase
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.get('/bookings')
server->routerBookings ++:app.use('/bookings',bookings)
routerBookings -> authMiddleware ++:protect(req, res, next)
alt !token 
    authMiddleware -> client :response
else token
    authMiddleware -> modelUser ++:findById(decoded.id)
    modelUser -> UsersDatabase ++: UserSchema
    UsersDatabase --> modelUser --: user
    modelUser -> authMiddleware --: user
    alt !user
        authMiddleware -> client :response
    else user
        authMiddleware -> controllersBookings ++: getBooking(req, res, next)
        controllersBookings -> modelBooking ++:findById(req.params.bookingId)
        modelBooking -> BookingsDatabase ++: BookingSchema
        BookingsDatabase --> modelBooking --: booking
        controllersBookings <-- modelBooking --:booking
        alt booking.user_id !== req.user.id && req.user.role !== "ADMIN"
            controllersBookings -> client :response
        else booking.user_id === req.user.id || req.user.role === "ADMIN"
            controllersBookings -> modelBooking ++:booking.deleteOne()
            modelBooking -> BookingsDatabase ++: BookingSchema
            BookingsDatabase --> modelBooking --: delete_booking
            controllersBookings <-- modelBooking --: delete_booking
            controllersBookings -> client --:response
        end
    end
end

@enduml
