@startuml Get Single Booking (GETONE)

header Get Single Booking Sequence Diagram
title "Get Single Booking (GETONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:User" as modelUser
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:users" as UsersDatabase
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client -> server ++:req.get('/bookings')
server -> routerBookings ++:app.use('/bookings',bookings)
routerBookings -> authMiddleware ++:protect(req, res, next)
alt !token 
    authMiddleware -> client :response
else token
    authMiddleware -> modelUser ++:findById(decoded.id)
    modelUser -> UsersDatabase ++: UserSchema
    UsersDatabase --> modelUser --: user
    modelUser -> authMiddleware --: user
    alt !user
        authMiddleware -> client :response
    else user
        authMiddleware -> controllersBookings ++: getBooking(req, res, next)
        controllersBookings -> modelBooking ++:findById(req.params.bookingId)
        modelBooking -> BookingsDatabase ++: BookingSchema
        BookingsDatabase --> modelBooking --: booking
        controllersBookings <-- modelBooking --:booking
        controllersBookings -> client --:response
    end
end


@enduml
