@startuml Update Booking (PUT)

header Update Booking Sequence Diagram
title "Update Booking (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.get('/bookings')
server->routerBookings ++:app.use('/bookings',bookings)
routerBookings -> controllersBookings ++: getBooking(req, res, next)
controllersBookings->modelBooking ++:findById(req.params.bookingId)
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: booking
controllersBookings <-- modelBooking --:booking
controllersBookings->modelBooking ++:findOne({ user_id: req.user.id, \ncompany_id, date })
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: duplicate_booking
controllersBookings <-- modelBooking --:duplicate_booking
controllersBookings->modelBooking ++:findByIdAndUpdate( booking_id, \nreq.body)
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: update_booking
controllersBookings <-- modelBooking --:update_booking
controllersBookings->client --:response

@enduml
