@startuml Update Profile (PUT)

header Update Profile Sequence Diagram
title "Update Profile (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UsersDatabase

client->server ++:req.put('/auth/profile')
server->routerAuth ++:app.use("/auth", auth)
routerAuth -> controllersAuth ++:editProfile(req, res, next)
controllersAuth->modelUser ++:findByIdAndUpdate(req.user.id,\n{ req.body.name, req.body.tel,\nreq.body.email })
modelUser ->UsersDatabase ++: UserSchema
UsersDatabase --> modelUser --: user
controllersAuth <-- modelUser --: user
controllersAuth->client --: response

@enduml